### ISSUE TITLE
Feature Request - Firefox

### ISSUE THREAD

**Issue by WXFanatics** [HowIChrgeLazer/FarmHand#5]
Are there any plans to make a firefox-extension port for this? I saw [this](https://blog.chosunghyun.com/porting-a-chrome-extension-to-firefox-add-on/) and wasn't sure if this was possible.

**Comment by mjljr** [comment]
So currently the main blocker to a quick port for Firefox is [manifest version 3 support](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/). This is something that is being targeted early 2022 to start accepting V3 manifest extensions (assuming no delays in their scheduling).

Unfortunately, without manifest version 3 support, the port to Firefox is not a 1:1 thing. At a minimum, would have to maintain different manifests, and potentially some code differences as well.

I'll keep an eye on Firefox manifest v3 support and if it's coming sooner rather than later, then should be easy to bring to Firefox. Edge and Chrome so far work 100% interchangeably, so just a matter of getting support within the Firefox browser for manifest v3.

**Comment by WXFanatics** [comment]
Ah, that makes sense. Here's to hoping to see this on Firefox in the future. Thank you for the response!
